const games = [
  {
    _id: 1,
    name: "Elden Ring",
    image: "/images/EldenRing.jpg",
    description: "lorem",
    platforms: {
      steam: true,
      xbox_one: true,
      playstation_5: true,
      playstation_4: true,
      xbox_series: true,
      nintendo_switch: false,
    },
    release_date: "25 Feb, 2022",
    price: 59.99,
    developper: "FromSoftware",
    rating: 4.5,
    numReviews: 53,
  },
  {
    _id: 2,
    name: "Death Stranding",
    image: "/images/DeathStranding.jpg",
    description: "lorem",
    platforms: {
      steam: true,
      xbox_one: true,
      playstation_5: true,
      playstation_4: true,
      xbox_series: true,
      nintendo_switch: false,
    },
    release_date: "30 Mar, 2022",
    price: 39.99,
    developper: "Kojima Productions",
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: 3,
    name: "Red Dead Redemption II",
    image: "/images/RDR2.jpg",
    description: "lorem",
    platforms: {
      steam: true,
      xbox_one: true,
      playstation_5: true,
      playstation_4: true,
      xbox_series: true,
      nintendo_switch: false,
    },
    release_date: "5 Dec, 2019",
    price: 59.99,
    developper: "Rockstar Games",
    rating: 4.5,
    numReviews: 18,
  },
  {
    _id: 3,
    name: "Cyberpunk 2077",
    image: "/images/Cyberpunk2077.jpg",
    description: "lorem",
    platforms: {
      steam: true,
      xbox_one: true,
      playstation_5: true,
      playstation_4: true,
      xbox_series: true,
      nintendo_switch: false,
    },
    release_date: "5 Dec, 2020",
    price: 59.99,
    developper: "CD Projekt Red",
    rating: 4.5,
    numReviews: 30,
  },
];

export default games;
